jobs:
  - name: nginx-manifest
    type: manifest
    steps:
      - IN: nginx-image
      - IN: runSh-Job
      - IN: params-resource
      - IN: docker-integration

  - name: runSh-Job
    type: runSh
    steps:
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 300
    on_success:
      - script: echo "successfully completed"

  - name: sample_pipelines_runCI
    type: runCI
    steps:
      - IN: runSh-Job
      - IN: params-resource
      - IN: docker-integration
      - OUT: nginx-image

#  - name: sample_node_runCI
#    type: runCI
#    steps:
#      - IN: sample_pipelines_runCI
